SodaMachineRazorUI/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace SodaMachineRazorUI.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SodaMachineRazorUI/Pages/GenerateAdmin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

namespace SodaMachineRazorUI.Pages
{
    public class GenerateAdminModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IConfiguration _config;

        public bool RoleCreated { get; set; }
        public string AdminUserId { get; set; }

        public GenerateAdminModel(RoleManager<IdentityRole> roleManager,
                                  UserManager<IdentityUser> userManager,
                                  IConfiguration config )
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _config = config;
        }

        public async Task OnGet()
        {
            var roleExists = await _roleManager.RoleExistsAsync("Admin");

            if(!roleExists)
            {
                await _roleManager.CreateAsync(new IdentityRole("Admin"));
                RoleCreated = true;
            }

            string userEmail = _config.GetValue<string>("AdminUser");
            var user = await _userManager.FindByEmailAsync(userEmail);

            if(user !=null)
            {
                await _userManager.AddToRoleAsync(user, "Admin");
                AdminUserId = user.Id;
            }
        }
    }
}

SodaMachineRazorUI/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace SodaMachineRazorUI.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

SodaMachineRazorUI/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace SodaMachineRazorUI.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

SodaMachineRazorUI/Pages/SodaMachine.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SodaMachineLibrary.Logic;
using SodaMachineLibrary.Models;

namespace SodaMachineRazorUI
{
    [Authorize]
    public class SodaMachineModel : PageModel
    {
        private readonly ISodaMachineLogic _sodaMachine;

        public decimal SodaPrice { get; set; }
        public decimal DepositedAmount { get; set; }
        public List<SodaModel> SodaOptions { get; set; }

        [BindProperty]
        public decimal Deposit { get; set; }

        [BindProperty]
        public SodaModel SelectedSoda { get; set; }

        //[BindProperty(SupportsGet = true)]
        public string UserId { get; set; }

        [BindProperty(SupportsGet = true)]
        public string OutputText { get; set; }

        [BindProperty(SupportsGet = true)]
        public string ErrorMessage { get; set; }

        public SodaMachineModel(ISodaMachineLogic sodaMachine)
        {
            _sodaMachine = sodaMachine;
        }

        public void OnGet()
        {
            if (string.IsNullOrWhiteSpace(UserId))
            {
                //UserId = Guid.NewGuid().ToString();
                UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            }

            SodaPrice = _sodaMachine.GetSodaPrice();
            DepositedAmount = _sodaMachine.GetMoneyInsertedTotal(UserId);
            SodaOptions = _sodaMachine.ListTypesOfSoda();
        }

        // Used for depositing coins
        public IActionResult OnPost()
        {
            UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (Deposit > 0)
            {
                _sodaMachine.MoneyInserted(UserId, Deposit);
            }

            //return RedirectToPage(new { UserId });
            return RedirectToPage();
        }

        // Used for requesting soda
        public IActionResult OnPostSoda()
        {
            UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var results = _sodaMachine.RequestSoda(SelectedSoda, UserId);
            OutputText = "";

            // Handle the response
            if (results.errorMessage.Length > 0)
            {
                ErrorMessage = results.errorMessage;
            }
            else
            {
                OutputText = $"Here is your { results.soda.Name }";

                if (results.change.Count > 0)
                {
                    OutputText += "<br><br>Here is your change:<br>";
                    results.change.ForEach(x => OutputText += $"{ x.Name }<br>");
                }
                else
                {
                    OutputText += "<br><br>You used exact change so there is no change to refund.";
                }
            }

            //return RedirectToPage(new { UserId, ErrorMessage, OutputText });
            return RedirectToPage(new { ErrorMessage, OutputText });
        }

        // Used for cancelling our deposit
        public IActionResult OnPostCancel()
        {
            UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            DepositedAmount = _sodaMachine.GetMoneyInsertedTotal(UserId);
            _sodaMachine.IssueFullRefund(UserId);

            OutputText = $"You have been refunded { String.Format("{0:C}", DepositedAmount) }";

            //return RedirectToPage(new { UserId, OutputText });
            return RedirectToPage(new { OutputText });
        }
    }
}

SodaMachineRazorUI/Pages/GenerateAdmin.cshtml
@page
@model SodaMachineRazorUI.Pages.GenerateAdminModel
@{
}

<h1>Genrate Admin</h1>

<h2>Role Created: @Model.RoleCreated</h2>
<h2>Admin User Id: @Model.AdminUserId</h2>

SodaMachineRazorUI/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SodaMachineRazorUI/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SodaMachineRazorUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">SodaMachineRazorUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/SodaMachine">Soda Machine</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SodaMachineRazorUI - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

SodaMachineRazorUI/Pages/SodaMachine.cshtml
@page
@model SodaMachineRazorUI.SodaMachineModel
@{
    ViewData["Title"] = "SodaMachine";
}

<h1>Soda Machine</h1>
<h5>Soda Price: @String.Format("{0:C}", Model.SodaPrice)</h5>
<h5>Deposited Amount: @String.Format("{0:C}", Model.DepositedAmount)</h5>

@if(!String.IsNullOrWhiteSpace(Model.ErrorMessage))
{
    <p class="text-danger">@Model.ErrorMessage</p>
}

<div class="row">
    <div class="col-sm-8">
        @foreach (var soda in Model.SodaOptions)
            {
        <div class="row">
            <div class="col-sm-8 soda-tab bg-secondary text-white">@soda.Name</div>
            <div class="col-sm-4">
                <form method="post" asp-page-handler="Soda">
                    <input type="hidden" asp-for="UserId" />
                    <input type="hidden" asp-for="SelectedSoda.Name" value="@soda.Name" />
                    <input type="hidden" asp-for="SelectedSoda.SlotOccupied" value="@soda.SlotOccupied" />
                    <button type="submit" class="btn btn-primary btn-soda">Buy</button>
                </form>
              
            </div>
        </div>
            }
        </div>
    <div class="col-sm-4">
        @Html.Raw(Model.OutputText)
    </div>
</div>


<div class="row">
    <div class="col-sm-4">
        <h3>Deposit Coins</h3>
        <div class="btn-group" role="group">
            <form method="post">
                <input type="hidden" asp-for="UserId" />
                <input type="hidden" asp-for="Deposit" value="0.05" />
                <button type="submit" class="btn btn-primary"> @String.Format("{0:C}", 0.05)</button>
            </form>
            <form method="post">
                <input type="hidden" asp-for="UserId" />
                <input type="hidden" asp-for="Deposit" value="0.10" />
                <button type="submit" class="btn btn-primary"> @String.Format("{0:C}", 0.10)</button>
            </form>
            <form method="post">
                <input type="hidden" asp-for="UserId" />
                <input type="hidden" asp-for="Deposit" value="0.25" />
                <button type="submit" class="btn btn-primary"> @String.Format("{0:C}", 0.25)</button>
            </form>         
        </div>
    </div>

    <div class="col-sm-4">
        <h3>Cancel Transaction</h3>
        <form method="post" asp-page-handler="Cancel">
            <input type="hidden" asp-for="UserId" />
            <button type="submit" class="btn btn-warning">Eject Money</button>
        </form>
      
    </div>
</div>

SodaMachineRazorUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SodaMachineRazorUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SodaMachineRazorUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SodaMachineRazorUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SodaMachineRazorUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>